### ISSUE TITLE
[Question] What to do about Delete methods of each route?

### ISSUE THREAD

**Issue by JoaoAlem** [thtsystems/open-visit#59]
**Context**
When writing the routes, i saw that companies schema have a active flag, but the others schemas don't have the flag.
And i know that we ain't gonna delete the data in database, so we'll add a flag for everyone.

**Solutions**
To make a standard, we can add active the same flag for every table, but in my opnion, i don't think that is a good idea, because personally i prefer something more verbose.
In my opnion, we can change the active flag to a date_delete field and add  two more fields: date_create and date_update.
This way we can even show to users since when they are members and for each update of the user, we can have last time updated time.

**Comment by ernestoresende** [comment]
That's a very good idea. You could make it as:

```typescript
  createdAt: timestamp("created_at", { withTimezone: false, mode: string }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: false, mode: string }).defaultNow().notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: false, mode: string }),
```

- `withTimezone: false` - We have a uniform ISO Date string, and if any timezone related operations are required, we handle then with client-side logic, instead of having to deal with UTC offsets at the server layer.
- `mode: "string"` - In `mode: "date"`, queries will return an JavaScript `Date()` object instead of the ISO string, which is undesirable since:
  1. JavaScript `Date` assume runtime timezones by default when making date transformations;
  2. We would have to serialize on the server, and deserialize back on the client in order to extract date information;

**Comment by JoaoAlem** [comment]
Thanks, how i don't have anything else to comment in this issue, i'm gonna close it.
